# Generated by Django 2.1 on 2018-03-29 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='c_las',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semes', models.IntegerField(default='1')),
                ('year', models.IntegerField(default='20102011')),
            ],
        ),
        migrations.CreateModel(
            name='dsclass',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='dssv',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='hocphan',
            fields=[
                ('mahp', models.CharField(default='', max_length=8, primary_key=True, serialize=False)),
                ('tenhp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sinhvien',
            fields=[
                ('mssv', models.CharField(default='', max_length=8, primary_key=True, serialize=False)),
                ('hoten', models.CharField(max_length=100)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.dssv')),
            ],
        ),
        migrations.CreateModel(
            name='taikhoan',
            fields=[
                ('username', models.CharField(default='', max_length=8, primary_key=True, serialize=False)),
                ('psd', models.CharField(max_length=20)),
                ('hoten', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='dsclass',
            name='taikhoan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.taikhoan'),
        ),
        migrations.AddField(
            model_name='c_las',
            name='dsclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.dsclass'),
        ),
        migrations.AddField(
            model_name='c_las',
            name='mahp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hocphan'),
        ),
    ]
